{% set name = "pygwalker" %}
{% set version = "0.1.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pygwalker-{{ version }}.tar.gz
  sha256: 86fc510aa4315c82f92f99174eb130e480fd9c2eeee651a7a580dc5709d66561

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --ignore-installed
  number: 0

requirements:
  host:
    - python >=3.6,<4.0
    - pip
    - hatchling
    - hatch-jupyter-builder
  run:
    - python >=3.6,<4.0
    - ipython
    - jinja2
    - pandas
    - typing_extensions
    - astor
    - ipywidgets
    - pydantic

test:
  imports:
    - pygwalker
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pygwalker/
  summary: 'pygwalker: Combining Jupyter Notebook with a Tableau-like UI'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gabrielcnr
    - Asm-Def
    - longxiaofei
